# Configuration Netlify pour IPTV Express
[build]
  # Commande de build
  command = "npm run build"
  # Dossier de publication
  publish = "dist"
  # Version Node.js
  [build.environment]
    NODE_VERSION = "18"

# Redirections pour SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    
    # Performance
    X-DNS-Prefetch-Control = "on"

# Headers spécifiques pour les assets statiques
[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache longue durée pour les assets avec hash
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Headers pour les polices
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Optimisations pour Supabase
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Authorization, Content-Type, apikey"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Configuration pour les fonctions (si utilisées plus tard)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Gestion des erreurs
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200

# Prévention du scan de sécurité sur certains endpoints
[[headers]]
  for = "/.well-known/*"
  [headers.values]
    X-Robots-Tag = "noindex"