// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbssebvzecsgcfjlqtqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdic3NlYnZ6ZWNzZ2NmamxxdHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNjcwMDgsImV4cCI6MjA3MTc0MzAwOH0.NBaNJ4mMtRieOhzbxY-MlYgWJg0Fzsvqe6ZLUiKA4rQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});